steps:
  # Step 1: Authenticate with Secret Manager to retrieve secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "Retrieving secrets..."
        export OPENAI_API_KEY=$(gcloud secrets versions access latest --secret=OPENAI_API_KEY)
        export TELEGRAM_BOT_TOKEN=$(gcloud secrets versions access latest --secret=TELEGRAM_BOT_TOKEN)

  # Step 2: Build the Docker image
  #telegram-bot was in us
  #telegram-bot-repo is in southeast1
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/telegram-bot-repo/telegram-bot:latest', '.']

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/telegram-bot-repo/telegram-bot:latest']

  # Step 4: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'telegram-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/telegram-bot'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--update-env-vars'
      - 'OPENAI_API_KEY=$_OPENAI_API_KEY,TELEGRAM_BOT_TOKEN=$_TELEGRAM_BOT_TOKEN'

timeout: 1200s
logsBucket: gs://telegram-bot-akask-bucket

substitutions:
  _OPENAI_API_KEY: "your-openai-api-key"
  _TELEGRAM_BOT_TOKEN: "your-telegram-bot-token"
