steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/telegram-bot-repo/telegram-bot:latest', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/telegram-bot-repo/telegram-bot:latest']

  # Step 3: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'telegram-bot'
      - '--image'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/telegram-bot-repo/telegram-bot:latest'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--update-secrets'
      - 'OPENAI_API_KEY=projects/$PROJECT_ID/secrets/OPENAI_API_KEY:latest,TELEGRAM_BOT_TOKEN=projects/$PROJECT_ID/secrets/TELEGRAM_BOT_TOKEN:latest'

  # Step 4: Set the Telegram webhook
  - name: 'curlimages/curl'
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "Retrieving Cloud Run URL..."
        TELEGRAM_BOT_URL=$(gcloud run services describe telegram-bot --region=asia-south1 --format="value(status.url)")
        if [[ -z "$TELEGRAM_BOT_URL" ]]; then
          echo "Error: Failed to retrieve Cloud Run URL"
          exit 1
        fi
        echo "Setting Telegram webhook to $TELEGRAM_BOT_URL/webhook..."
        TELEGRAM_BOT_TOKEN=$(gcloud secrets versions access latest --secret=TELEGRAM_BOT_TOKEN)
        if [[ -z "$TELEGRAM_BOT_TOKEN" ]]; then
          echo "Error: Failed to retrieve TELEGRAM_BOT_TOKEN"
          exit 1
        fi
        curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/setWebhook" \
             -d "url=$TELEGRAM_BOT_URL/webhook"
timeout: 1200s
logsBucket: gs://telegram-bot-akask-bucket
